version: '3.8'

services:
  app:
    build: .
    container_name: laravel_app
    ports:
      - "8000:80"
    volumes:
      # Volume pour le développement persistant
      - ./:/var/www/html
      # Exclusion des dossiers spécifiques qui ne doivent pas être montés depuis l'hôte
      - /var/www/html/vendor
      - /var/www/html/node_modules
      - /var/www/html/storage/framework/cache
      - /var/www/html/storage/framework/sessions
      - /var/www/html/storage/framework/views
    depends_on:
      - db
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: user
      DB_PASSWORD: password
      APP_ENV: local
      APP_DEBUG: "true"

  db:
    image: mysql:8.0
    container_name: laravel_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
