name: Docker Image CI

on:
  push:
    branches:
      - feature-CI

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install Docker (Official Script)
        run: |
          curl -fsSL https://get.docker.com | sh
          sudo usermod -aG docker $USER
          sudo systemctl restart docker

      - name: Check Docker installation
        run: |
          docker --version
          docker-compose version || echo "docker-compose not found"

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Build and start Docker containers
        run: docker-compose up --build -d

      - name: List running containers
        run: docker ps -a

      - name: Stop and clean up containers
        run: docker-compose down
